### ISSUE TITLE
Import errors with the WAC and UniqueCarrier fields

### ISSUE THREAD

**Issue by hannes** [eyalroz/usdt-ontime-tools#12]
Great scripts! However, I was trying to run the import and got
````
ERROR = !Failed to import table 'ontime', line 1105 field originwac 'tinyint' expected in '826'
ERROR = !Failed to import table 'ontime', line 1001 field destwac 'tinyint' expected in '268'
````
on a bunch of files, suggest to change these types into `SMALLINT`.

**Comment by hannes** [comment]
Same with 
`ERROR = !Failed to import table 'ontime', line 396485 field uniquecarrier 'char(2)' expected in 'PA (1)'`

**Comment by eyalroz** [comment]
This is kind of strange... can you tell me which month's data exhibits this behavior?

**Comment by hannes** [comment]
Very early, 1987 I think

**Comment by eyalroz** [comment]
Found some files with the WAC problem . Somehow this slipped by me, because later on there are 52 WAC values for 52 states/territories:
````
select originstate, originwac from ontime group by originstate, originwac order by originstate asc;
````
and none of them is 268. Will look into it.

**Comment by eyalroz** [comment]
So, 286 is Puerto Rico and 826 is Guam, and for some reason they don't appear in the data during 2000-2008 at least. Weird. Will change the types to SMALLINT for WACs and VARCHAR(6) for UniqueCarrier.
